apiVersion: v2
name: maroctour
description: A Helm chart for MarocTour application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - maroctour
  - tourism
  - morocco
maintainers:
  - name: MarocTour Team
    email: dev@maroctour.ma

